#Input.cfg
#configuration of key assignments 
#please use the convention:
#     keyCharacterInCapital=Assignment
#     possible Assignments visisble in availableInputCommands.cfg from engine
#     example: W=CameraUp

#Options
P=Pause
ESC=OpenMenu

#Gameplay
W=CameraUp
A=CameraLeft
S=CameraDown
D=CameraRight
